version: '3'
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: 041216
      POSTGRES_USER: postgres
      POSTGRES_DB: ipdv
    volumes:
      - .api/pgdata:/var/lib/postgresql/data
    ports: 
      - 5432:5432  
  app:
    container_name: ipdv
    restart: always
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    
